### ISSUE TITLE
maybe a dumb issue again

### ISSUE THREAD

**Issue by rk3333333** [freedownloadhere/AutoPowderGrinder#1]
so i've compiled this project into a dll and injected it into forge 1.8.9 there are no issues with the injection but then the console goes crazt and shows this: 
`[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 10 ms
[walkMap iteration] Timer ran for 11 ms
[walkMap iteration] Timer ran for 10 ms
...`

i've put a location near my location just to be shure maybe it couldn't find a path bc the chunks weren't loaded but ye

**Comment by fdh911** [comment]
That's debug code, sorry. It's just a timer I left in there to check whether the walk map is being generated.

**Comment by rk3333333** [comment]
but the problem is that it doesn't do anything i've seen the code where it tries to place glowstone blocks (i think glowstone) but it doesn't do that

**Comment by fdh911** [comment]
alright, I'll solve this eventually. if you want to use the pathfinder, check out my pathfinder-project repo, I just updated it, check the readme.

**Comment by rk3333333** [comment]
ok
